### PR TITLE
initial website, jekyll base

### PR DESCRIPTION
**Pull request by sreev**
this is built website artifacts.

### CODE REVIEW

**Comment by joshelser** [comment]
You would not commit the Gemfile and Gemfile.lock files to this branch. These should only exist in the branch containing the Jekyll project. Please remove them, thanks.

**Comment by joshelser** [comment]
```
$ git push origin
Total 0 (delta 0), reused 0 (delta 0)
To https://git-wip-us.apache.org/repos/asf/incubator-gossip.git
 * [new branch]      site-src -> site-src
```

**Comment by joshelser** [comment]
Thanks for removing those.

Some other things that need fixing: have you seen http://incubator.apache.org/guides/branding.html? You need to make sure you refer to Apache Gossip as an incubator project; "Apache Gossip (incubating)" is a common choice. You also must have the listed incubator disclaimer on the branding page. Finally, you should have links to ASF "How it works" page (http://www.apache.org/foundation/how-it-works.html), the ASL http://www.apache.org/licenses/, the sponsorship page (http://www.apache.org/foundation/sponsorship.html), and the ASF thanks page (http://www.apache.org/foundation/thanks.html).

Check out Rya's website: http://rya.incubator.apache.org/. They have all of these points covered.

**Comment by sreev** [comment]
new checkins based on your inputs, @joshelser . thank you.
finding more content to add.

**Comment by joshelser** [comment]
Looks like Github won't auto-close this issue (even though I told it to). If you can close this one and #6, that'd be great, @sreev.

**Comment by sreev** [comment]
done. thank you, josh.

**Pull request closed without merging**
